[package]
name = "zoom-webhook-schema"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
insta = { version = "1", features = ["yaml"] }
serde_json = "1"
